// Datos semilla de tarifas — portado 1:1 desde seed_data.py (programa cotizador)
// Cada fila: { plan, tipo, nivel_ingreso, regimen_tributario,
//              num_comprobantes, num_trabajadores, regimen_laboral, monto }

import type { TarifaFila } from "./types";

export const TARIFA_EMPRESARIAL_2026: TarifaFila[] = [
  // Contabilidad (Mype)
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 500 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/50,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 650 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/70,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 750 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 900 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/150,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1200 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/250,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1400 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/300,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1600 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/500,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1800 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/700,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2000 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/1,000,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2200 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Desde S/1,000,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2300 },
  // Contabilidad (General)
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 600 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/50,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 750 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/70,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 850 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1000 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/150,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1300 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/250,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1500 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/300,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1700 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/500,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1900 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/700,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2100 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/1,000,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2300 },
  { plan: "Empresarial 2026", tipo: "contabilidad", nivel_ingreso: "Desde S/1,000,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2400 },
  // Planilla
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Base", monto: 50 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Remype", monto: 100 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "Remype", monto: 250 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "Remype", monto: 450 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "Remype", monto: 600 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "Remype", monto: 750 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 25 trabajadores", regimen_laboral: "Remype", monto: 900 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "Remype", monto: 1000 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Pequena", monto: 150 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "Pequena", monto: 375 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "Pequena", monto: 675 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "Pequena", monto: 900 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "Pequena", monto: 1125 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 25 trabajadores", regimen_laboral: "Pequena", monto: 1350 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "Pequena", monto: 1500 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "General", monto: 180 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "General", monto: 450 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "General", monto: 810 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "General", monto: 1080 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "General", monto: 1350 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 25 trabajadores", regimen_laboral: "General", monto: 1620 },
  { plan: "Empresarial 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "General", monto: 1800 },
];

export const TARIFA_INTEGRAL_2026: TarifaFila[] = [
  // Contabilidad
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/10,000", regimen_tributario: "RUS", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/10,000", regimen_tributario: "Especial", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Especial", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 500 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Especial", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 600 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/10,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 500 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 550 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 650 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/50,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 750 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 900 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/150,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1200 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/250,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1400 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/300,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1600 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/500,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1800 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/700,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2000 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/1,000,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2200 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Desde S/1,000,000", regimen_tributario: "Mype", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2300 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/10,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 600 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 650 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 750 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/50,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 850 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1000 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/150,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1300 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/250,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1500 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/300,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1700 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/500,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1900 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/700,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2100 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Hasta S/1,000,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2300 },
  { plan: "Integral 2026", tipo: "contabilidad", nivel_ingreso: "Desde S/1,000,000", regimen_tributario: "General", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2400 },
  // Planilla
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Base", monto: 50 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Remype", monto: 100 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "Remype", monto: 250 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "Remype", monto: 450 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "Remype", monto: 600 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "Remype", monto: 750 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 25 trabajadores", regimen_laboral: "Remype", monto: 900 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "Remype", monto: 1000 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Pequena", monto: 150 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "Pequena", monto: 375 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "Pequena", monto: 675 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "Pequena", monto: 900 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "Pequena", monto: 1125 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 25 trabajadores", regimen_laboral: "Pequena", monto: 1350 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "Pequena", monto: 1500 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "General", monto: 180 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "General", monto: 450 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "General", monto: 810 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "General", monto: 1080 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "General", monto: 1350 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 25 trabajadores", regimen_laboral: "General", monto: 1620 },
  { plan: "Integral 2026", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "General", monto: 1800 },
  // Asesoria
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/10,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/50,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 300 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 300 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/150,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 350 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/250,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 350 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/300,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/500,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 500 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/700,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 700 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Hasta S/1,000,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 700 },
  { plan: "Integral 2026", tipo: "asesoria", nivel_ingreso: "Desde S/1,000,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1000 },
];

export const TARIFA_ADICIONAL: TarifaFila[] = [
  // Recursos Humanos
  { plan: "Adicional", tipo: "SCTR", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "SCTR_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "licencia_maternidad", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "licencia_maternidad_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "subsidios", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Adicional", tipo: "subsidios_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "representacion_autoridad", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "construccion_civil", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "construccion_civil_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "asesoria_laboral_permanente", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "asesoria_laboral_permanente_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "plantillas_laborales", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "plantillas_laborales_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "modelo_contrato", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "modelo_contrato_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "modelo_contrato_clausulas", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "modelo_contrato_clausulas_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "seguimiento_SUNAFIL", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "seguimiento_SUNAFIL_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "respuesta_SUNAFIL", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "respuesta_SUNAFIL_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "atencion_ministerio", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "atencion_ministerio_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "capacitacion_anual", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "capacitacion_anual_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 250 },
  { plan: "Adicional", tipo: "acta_salud_seguridad", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 60 },
  { plan: "Adicional", tipo: "acta_salud_seguridad_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "seguro_vida_ley", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "seguro_vida_ley_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  // Contratos legales
  { plan: "Adicional", tipo: "contrato_trabajo_basico", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "contrato_trabajo_basico_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "contrato_trabajo_especial", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "contrato_trabajo_especial_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_arrendamiento_basico", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "contrato_arrendamiento_basico_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "contrato_arrendamiento_especial", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "contrato_arrendamiento_especial_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_mutuo_basico", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "contrato_mutuo_basico_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_mutuo_especial", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 300 },
  { plan: "Adicional", tipo: "contrato_mutuo_especial_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 500 },
  { plan: "Adicional", tipo: "contrato_mandato_basico", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "contrato_mandato_basico_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_mandato_especial", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_mandato_especial_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Adicional", tipo: "contrato_cesion_cuenta", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_cesion_cuenta_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Adicional", tipo: "contrato_licencia_marca", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_licencia_marca_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Adicional", tipo: "contrato_trabajo_extranjero", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Adicional", tipo: "contrato_trabajo_extranjero_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Adicional", tipo: "adenda_contratos", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "adenda_contratos_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Adicional", tipo: "respuesta_SUNAFIL_simple", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 20 },
  { plan: "Adicional", tipo: "respuesta_SUNAFIL_simple_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "respuesta_SUNAT_simple", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Adicional", tipo: "respuesta_SUNAT_simple_externo", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  // Servicios especiales
  { plan: "Adicional", tipo: "registro_marca_INDECOPI_Piura", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1500 },
  { plan: "Adicional", tipo: "registro_marca_INDECOPI_otros", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1500 },
  { plan: "Adicional", tipo: "constitucion_empresa", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1000 },
];

export const TARIFA_INTEGRAL_EXTERNO: TarifaFila[] = [
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 800 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 1550 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/200,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2300 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/250,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 2650 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/300,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 3500 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/500,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 4400 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Hasta S/1,000,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 6300 },
  { plan: "Integral Externo", tipo: "contable_legal", nivel_ingreso: "Desde S/1,100,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 7500 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "", monto: 250 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "", monto: 450 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 15 trabajadores", regimen_laboral: "", monto: 600 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 20 trabajadores", regimen_laboral: "", monto: 700 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 30 trabajadores", regimen_laboral: "", monto: 900 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 40 trabajadores", regimen_laboral: "", monto: 1000 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 50 trabajadores", regimen_laboral: "", monto: 1200 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 80 trabajadores", regimen_laboral: "", monto: 1800 },
  { plan: "Integral Externo", tipo: "laboral", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 100 trabajadores", regimen_laboral: "", monto: 2200 },
];

export const TARIFA_RER: TarifaFila[] = [
  { plan: "Régimen Especial", tipo: "contabilidad", nivel_ingreso: "Hasta S/10,000", regimen_tributario: "Especial", num_comprobantes: "100", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Régimen Especial", tipo: "contabilidad", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Especial", num_comprobantes: "200", num_trabajadores: "", regimen_laboral: "", monto: 300 },
  { plan: "Régimen Especial", tipo: "contabilidad", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Especial", num_comprobantes: "200", num_trabajadores: "", regimen_laboral: "", monto: 400 },
  { plan: "Régimen Especial", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 2 trabajadores", regimen_laboral: "Remype", monto: 100 },
  { plan: "Régimen Especial", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 5 trabajadores", regimen_laboral: "Remype", monto: 250 },
  { plan: "Régimen Especial", tipo: "planilla", nivel_ingreso: "", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "Hasta 10 trabajadores", regimen_laboral: "Remype", monto: 450 },
];

export const TARIFA_DECLARACION_EXPRESS: TarifaFila[] = [
  // RUS
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/5,000", regimen_tributario: "RUS", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/5,000", regimen_tributario: "RUS", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 120 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/5,000", regimen_tributario: "RUS", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 140 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/8,000", regimen_tributario: "RUS", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/8,000", regimen_tributario: "RUS", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 170 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/8,000", regimen_tributario: "RUS", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 190 },
  // Planilla RUS
  { plan: "Declaración Express", tipo: "pdt_planilla", nivel_ingreso: "Hasta S/5,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  { plan: "Declaración Express", tipo: "pdt_planilla", nivel_ingreso: "Hasta S/8,000", regimen_tributario: "", num_comprobantes: "", num_trabajadores: "", regimen_laboral: "", monto: 50 },
  // Especial
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Especial", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 80 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Especial", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Especial", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 120 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Especial", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Especial", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 120 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Especial", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 140 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Especial", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Especial", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 170 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Especial", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 180 },
  // Mype
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 100 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 120 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/20,000", regimen_tributario: "Mype", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 140 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 120 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 140 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/30,000", regimen_tributario: "Mype", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 160 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 150 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 170 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/40,000", regimen_tributario: "Mype", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 190 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/80,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 180 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/80,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/80,000", regimen_tributario: "Mype", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 220 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 100 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 200 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "Mype", num_comprobantes: "Hasta 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 220 },
  { plan: "Declaración Express", tipo: "pdt", nivel_ingreso: "Hasta S/100,000", regimen_tributario: "Mype", num_comprobantes: "Más de 200 comprobantes", num_trabajadores: "", regimen_laboral: "", monto: 250 },
];

export const TODAS_LAS_TARIFAS: TarifaFila[] = [
  ...TARIFA_EMPRESARIAL_2026,
  ...TARIFA_INTEGRAL_2026,
  ...TARIFA_INTEGRAL_EXTERNO,
  ...TARIFA_RER,
  ...TARIFA_DECLARACION_EXPRESS,
  ...TARIFA_ADICIONAL,
];
